server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
  datasource:
    url: jdbc:h2:file:~/bnc-h2-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    initialize: false
    username: admin
    password:
  jpa:
    hibernate:
    ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true